=== cngshow/prisme/config/tds/TerminologyConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by Brent Jacox (Department of Veterans Affairs) -->
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by David (Department of Veteran Affairs) -->
<!-- edited by Dan Armbrust to add support for TreeVUID and CPDP - which help link subsets to a concept in the tree, and 
  inform about what properties are intended to be attached to what type (description or concept)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Active" type="xs:boolean"/>
	<xs:element name="AllowEmpty" type="xs:boolean"/>
	<xs:element name="Inverse" type="xs:boolean"/>
	<xs:element name="IsList" type="xs:boolean"/>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="TreeVUID" type="xs:long" />  <!-- The VUID of the concept in the tree that organizes the subset and/or domain members.  -->
	<!-- Informs as to whether a property type is applicable to a concept or a description -->
	<xs:simpleType name="CPDP" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CP" />
			<xs:enumeration value="DP" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:sequence>
					<xs:element name="CPDP" type="CPDP" />
				</xs:sequence>
				<xs:element ref="AllowEmpty"/>
				<xs:element ref="IsList"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropertyType" type="xs:string"/>
	<xs:element name="PropertyValue" type="xs:string"/>
	<xs:element name="Relationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="AllowEmpty"/>
				<xs:element ref="IsList"/>
				<xs:sequence minOccurs="0">
					<xs:element ref="Inverse"/>
					<xs:sequence minOccurs="0">
						<xs:element ref="PropertyType"/>
						<xs:element ref="PropertyValue"/>
					</xs:sequence>
				</xs:sequence>
				<xs:element ref="IncludeWithChange" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Relationships">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Relationship" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Designation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="AllowEmpty"/>
				<xs:element ref="IsList"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MapSet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="VUID"/>
				<xs:element name="GemContent" type="xs:boolean" minOccurs="0"/>
				<xs:element name="WebServiceAccessible" type="xs:boolean" minOccurs="0"/>
				<xs:element name="SourceType" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ConceptCode"/>
							<xs:enumeration value="DesignationCode"/>
							<xs:enumeration value="DesignationName"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="TargetType" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ConceptCode"/>
							<xs:enumeration value="DesignationCode"/>
							<xs:enumeration value="DesignationName"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Designations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Designation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Dependencies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DependentSubset" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DependentSubset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SubsetName"/>
				<xs:element ref="RelationshipName"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubsetName" type="xs:string"/>
	<xs:element name="RelationshipName" type="xs:string"/>
	<xs:element name="Subset">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="TreeVUID" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Active"/>
				<xs:element ref="Dependencies" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="Properties"/>
				<xs:element ref="Relationships"/>
				<xs:element ref="Designations" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="IncludeWithChange" type="xs:string"/>
	<xs:element name="Domains">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Domain" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Domain">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="TreeVUID" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Subset" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="CodeSystem" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MapSets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MapSet" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodeSystem">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="VUID"/>
				<xs:element ref="Properties"/>
				<xs:element ref="Relationships" minOccurs="0"/>
				<xs:element ref="Designations" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Terminology">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Domains"/>
				<xs:element ref="States"/>
				<xs:element ref="MapSets" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="States">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="State" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="State">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VUID" type="xs:long"/>
	<xs:element name="Type" type="xs:string"/>
</xs:schema>

=== cngshow/prisme/config/tds/TerminologyConfig_notes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 (http://www.altova.com)-->
<Terminology xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="C:\bea\user_projects\domains\VETSdomain\autodeploy\config\TerminologyConfig.xsd">
	<Domains>//All Domains are top level.  We will Display for each Domain all the subsets.  Selecting a domain selects all subsets.  Or individual subsets can be selected
//Randy gave us a new sample file with mapsets.  We can see these on the wireframes, but he needs to get back with us on what data to peel out.  Randy wants to discuss removing this from checksum page
		<Domain>
			<Name>Allergy</Name>
			<Subset>
				<Name>Reactions</Name>
				<Active>true</Active>
				<Properties>// For these properties it tells us which to use for checksum calculation
					<Property>
						<Name>Search_Term</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>true</IsList>
					</Property>
				</Properties>
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>Reactants</Name>
				<Active>true</Active>//If not active no checksums in vista, do not display if false
				<Properties>
					<Property>//order of these properties matter, preserve it.
						<Name>Allergy_Type</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>Search_Term</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>true</IsList>
					</Property>
				</Properties>
				<Relationships>//Relationships are involved in the checksums
					<Relationship>
						<Name>has_drug_ingredient</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>true</IsList>
					</Relationship>
					<Relationship>
						<Name>has_drug_class</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>true</IsList>
					</Relationship>
				</Relationships>
				<Designations />//We can ignore.
			</Subset>
		</Domain>
		<Domain>
			<Name>Immunizations</Name>
			<Subset>
				<Name>Immunization Procedure</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>VistA_Short_Name</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships>
					<Relationship>
						<Name>vista_replaced_by</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
				</Relationships>
				<Designations />
			</Subset>
			<Subset>
				<Name>Skin Test</Name>
				<Active>true</Active>
				<Properties />
				<Relationships>
					<Relationship>
						<Name>vista_replaced_by</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
				</Relationships>
				<Designations />
			</Subset>
		</Domain>
		<Domain>
			<Name>National Drug File</Name>
			<Subset>
				<Name>Drug Classes</Name>
				<Active>false</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>Drug Ingredient</Name>
				<Active>false</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
		</Domain>
		<Domain>
			<Name>Pharmacy</Name>
			<Subset>
				<Name>Medication Routes</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>FDB_Med_Route</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships>
					<Relationship>
						<Name>vista_replaced_by</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
				</Relationships>
				<Designations />
			</Subset>
		</Domain>
		<Domain>
			<Name>Orders</Name>
			<Subset>
				<Name>Order Status</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>VistA_Short_Name</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Abbreviation</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Description</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>Nature of Order</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>VistA_Abbreviation</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Interaction</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Door</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Discontinued</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Create_Action</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Signature_Status</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships />
				<Designations />
			</Subset>
		</Domain>
		<Domain>
			<Name>TIU</Name>
			<Subset>
				<Name>TIU Status</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>VistA_Abbreviation</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Interaction</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Description</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU Doctype</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU Role</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU SMD</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU Service</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU Setting</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>TIU Titles</Name>
				<Active>true</Active>
				<Properties />
				<Relationships>
					<Relationship>
						<Name>has_SMD</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
					<Relationship>
						<Name>has_role</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
					<Relationship>
						<Name>has_setting</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
					<Relationship>
						<Name>has_service</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
					<Relationship>
						<Name>has_doctype</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Relationship>
				</Relationships>
				<Designations />
			</Subset>
		</Domain>
		<Domain>
			<Name>Vitals</Name>
			<Subset>
				<Name>Vital Types</Name>
				<Active>true</Active>
<!--			
				<Dependencies>
					<DependentSubset>
						<SubsetName>Vital Qualifiers</SubsetName>
						<RelationshipName>has_qualifier</RelationshipName>
					</DependentSubset>
				</Dependencies>
				-->
				<Properties>
					<Property>
						<Name>VistA_Short_Name</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Type_Rate</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Rate_Input_Transform</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_Type_Rate_Help</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
					<Property>
						<Name>VistA_PCE_Abbreviation</Name>
						<AllowEmpty>true</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>Vital Categories</Name>
				<Active>true</Active>
				<Properties />
				<Relationships />
				<Designations />
			</Subset>
			<Subset>
				<Name>Vital Qualifiers</Name>
				<Active>true</Active>
				<Properties>
					<Property>
						<Name>VistA_Short_Name</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
					</Property>
				</Properties>
				<Relationships>
					<Relationship>
						<Name>has_qualifier</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>true</IsList>
						<Inverse>false</Inverse>
					</Relationship>
<!--					
					<Relationship>
						<Name>has_qualifier</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>true</IsList>
						<Inverse>true</Inverse>
						<IncludeWithChange>has_VistA_category</IncludeWithChange>
					</Relationship>
					-->
					<Relationship>
						<Name>has_VistA_category</Name>
						<AllowEmpty>false</AllowEmpty>
						<IsList>false</IsList>
						<Inverse>false</Inverse>
					</Relationship>
				</Relationships>
				<Designations />
			</Subset>
		</Domain>
	</Domains>
	<States>
		<State>
			<Name>Created</Name>
			<Type>Initial</Type>
		</State>
		<State>
			<Name>Ready To Review</Name>
			<Type>Ready To Review</Type>
		</State>
		<State>
			<Name>Under Review</Name>
			<Type>Under Review</Type>
		</State>
		<State>
			<Name>Failed Review</Name>
			<Type>Failed Review</Type>
		</State>
		<State>
			<Name>Ready To Test</Name>
			<Type>Ready To Test</Type>
		</State>
		<State>
			<Name>In Test</Name>
